routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
//use App\Http\Middleware\FilledProfile;
use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('home');

//Route::get('/', function (){
//	return view('welcome');
//});

Auth::routes();

Route::get('/cabinet', 'Cabinet\HomeController@index')->name('cabinet');

//Route::get('/cabinet', 'Auth\LoginController@index')->name('login');

Route::get('/verify/{token})', 'Auth\RegisterController@verify')->name('register.verify');

//Route::get('/cabinet', 'Cabinet\HomeController@index')->name('cabinet.home');

Route::group(
	[
		'prefix' => 'cabinet',
		'as' => 'cabinet.',
		'namespace' => 'Cabinet',
		'middleware' => ['auth'],
	],
	function () {
		Route::get('/', 'HomeController@index')->name('home');

//		Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
//			Route::get('/', 'ProfileController@index')->name('home');
//			Route::get('/edit', 'ProfileController@edit')->name('edit');
//			Route::put('/update', 'ProfileController@update')->name('update');
//			Route::post('/phone', 'PhoneController@request');
//			Route::get('/phone', 'PhoneController@form')->name('phone');
//			Route::put('/phone', 'PhoneController@verify')->name('phone.verify');
//
//			Route::post('/phone/auth', 'PhoneController@auth')->name('phone.auth');
//		});
//
//		Route::get('favorites', 'FavoriteController@index')->name('favorites.index');
//		Route::delete('favorites/{advert}', 'FavoriteController@remove')->name('favorites.remove');
//
//		Route::resource('tickets', 'TicketController')->only(['index', 'show', 'create', 'store', 'destroy']);
//		Route::post('tickets/{ticket}/message', 'TicketController@message')->name('tickets.message');

//		Route::group([
//			'prefix' => 'adverts',
//			'as' => 'adverts.',
//			'namespace' => 'Adverts',
//			'middleware' => [App\Http\Middleware\FilledProfile::class],
//		], function () {
//			Route::get('/', 'AdvertController@index')->name('index');
//			Route::get('/create', 'CreateController@category')->name('create');
//			Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
//			Route::get('/create/advert/{category}/{region?}', 'CreateController@advert')->name('create.advert');
//			Route::post('/create/advert/{category}/{region?}', 'CreateController@store')->name('create.advert.store');
//
//			Route::get('/{advert}/edit', 'ManageController@editForm')->name('edit');
//			Route::put('/{advert}/edit', 'ManageController@edit');
//			Route::get('/{advert}/photos', 'ManageController@photosForm')->name('photos');
//			Route::post('/{advert}/photos', 'ManageController@photos');
//			Route::get('/{advert}/attributes', 'ManageController@attributesForm')->name('attributes');
//			Route::post('/{advert}/attributes', 'ManageController@attributes');
//			Route::post('/{advert}/send', 'ManageController@send')->name('send');
//			Route::post('/{advert}/close', 'ManageController@close')->name('close');
//			Route::delete('/{advert}/destroy', 'ManageController@destroy')->name('destroy');
		});

Route::group(
	[
		'prefix' => 'admin',
		'as' => 'admin.',
		'namespace' => 'Admin',
		'middleware' => ['auth', 'can:admin-panel'],
	],
	function () {
//		Route::post( '/ajax/upload/image', 'UploadController@image' )->name( 'ajax.upload.image' );

		Route::get( '/', 'HomeController@index' )->name( 'home' );
		Route::resource( 'users', 'UserController' );
		Route::get( '/users/{user}/roles', 'UserController@changeRoleView' )->name( 'user.roles' );
		Route::post( '/users/{user}/roles-edit', 'UserController@changeRoleEdit' )->name( 'user.roles-edit' );
//		Route::post( '/users/{user}/verify', 'UsersController@verify' )->name( 'users.verify' );

		Route::resource( 'regions', 'RegionController' );
		Route::group(['prefix' => 'adverts', 'as' => 'adverts.', 'namespace' => 'Adverts'], function () {

			Route::resource( 'categories', 'CategoryController' );

			Route::group(['prefix' => 'categories/{category}', 'as' => 'categories.'], function () {
				Route::post('/first', 'CategoryController@first')->name('first');
				Route::post('/up', 'CategoryController@up')->name('up');
				Route::post('/down', 'CategoryController@down')->name('down');
				Route::post('/last', 'CategoryController@last')->name('last');
				Route::resource('attributes', 'AttributeController')->except('index');
			});
		});
//
//		Route::resource( 'pages', 'PageController' );
//
//		Route::group( [ 'prefix' => 'pages/{page}', 'as' => 'pages.' ], function () {
//			Route::post( '/first', 'PageController@first' )->name( 'first' );
//			Route::post( '/up', 'PageController@up' )->name( 'up' );
//			Route::post( '/down', 'PageController@down' )->name( 'down' );
//			Route::post( '/last', 'PageController@last' )->name( 'last' );
//		} );
	});

app/Http/Controllers/Admin/Adverts/AdvertController.php
<?php
//
//namespace App\Http\Controllers\Admin\Adverts;
//
//use App\Entity\Adverts\Advert\Advert;
//use App\Entity\User;
//use App\Http\Controllers\Controller;
//use App\Http\Requests\Adverts\AttributesRequest;
//use App\Http\Requests\Adverts\EditRequest;
//use App\Http\Requests\Adverts\PhotosRequest;
//use App\Http\Requests\Adverts\RejectRequest;
//use App\UseCases\Adverts\AdvertService;
//use Illuminate\Http\Request;
//
//class AdvertController extends Controller
//{
//    private $service;
//
//    public function __construct(AdvertService $service)
//    {
//        $this->service = $service;
//        $this->middleware('can:manage-adverts');
//    }
//
//    public function index(Request $request)
//    {
//        $query = Advert::orderByDesc('updated_at');
//
//        if (!empty($value = $request->get('id'))) {
//            $query->where('id', $value);
//        }
//
//        if (!empty($value = $request->get('title'))) {
//            $query->where('title', 'like', '%' . $value . '%');
//        }
//
//        if (!empty($value = $request->get('user'))) {
//            $query->where('user_id', $value);
//        }
//
//        if (!empty($value = $request->get('region'))) {
//            $query->where('region_id', $value);
//        }
//
//        if (!empty($value = $request->get('category'))) {
//            $query->where('category_id', $value);
//        }
//
//        if (!empty($value = $request->get('status'))) {
//            $query->where('status', $value);
//        }
//
//        $adverts = $query->paginate(20);
//
//        $statuses = Advert::statusesList();
//
//        $roles = User::rolesList();
//
//        return view('admin.adverts.adverts.index', compact('adverts', 'statuses', 'roles'));
//    }
//
//    public function editForm(Advert $advert)
//    {
//        return view('adverts.edit.advert', compact('advert'));
//    }
//
//    public function edit(EditRequest $request, Advert $advert)
//    {
//        try {
//            $this->service->edit($advert->id, $request);
//        } catch (\DomainException $e) {
//            return back()->with('error', $e->getMessage());
//        }
//
//        return redirect()->route('adverts.show', $advert);
//    }
//
//    public function attributesForm(Advert $advert)
//    {
//        return view('adverts.edit.attributes', compact('advert'));
//    }
//
//    public function attributes(AttributesRequest $request, Advert $advert)
//    {
//        try {
//            $this->service->editAttributes($advert->id, $request);
//        } catch (\DomainException $e) {
//            return back()->with('error', $e->getMessage());
//        }
//
//        return redirect()->route('adverts.show', $advert);
//    }
//
//    public function photosForm(Advert $advert)
//    {
//        return view('adverts.edit.photos', compact('advert'));
//    }
//
//    public function photos(PhotosRequest $request, Advert $advert)
//    {
//        try {
//            $this->service->addPhotos($advert->id, $request);
//        } catch (\DomainException $e) {
//            return back()->with('error', $e->getMessage());
//        }
//
//        return redirect()->route('adverts.show', $advert);
//    }
//
//    public function moderate(Advert $advert)
//    {
//        try {
//            $this->service->moderate($advert->id);
//        } catch (\DomainException $e) {
//            return back()->with('error', $e->getMessage());
//        }
//
//        return redirect()->route('adverts.show', $advert);
//    }
//
//    public function rejectForm(Advert $advert)
//    {
//        return view('admin.adverts.adverts.reject', compact('advert'));
//    }
//
//    public function reject(RejectRequest $request, Advert $advert)
//    {
//        try {
//            $this->service->reject($advert->id, $request);
//        } catch (\DomainException $e) {
//            return back()->with('error', $e->getMessage());
//        }
//
//        return redirect()->route('adverts.show', $advert);
//    }
//
//    public function destroy(Advert $advert)
//    {
//        try {
//            $this->service->remove($advert->id);
//        } catch (\DomainException $e) {
//            return back()->with('error', $e->getMessage());
//        }
//
//        return redirect()->route('admin.adverts.adverts.index');
//    }
//}

app/Http/Controllers/Admin/Adverts/AttributeController.php
<?php

namespace App\Http\Controllers\Admin\Adverts;

use App\Entity\Adverts\Attributes;
use App\Entity\Adverts\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class AttributeController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:admin-panel');
    }

    public function create(Category $category)
    {
        $types = Attributes::typesList();

        return view('admin.adverts.categories.attributes.create', compact('category', 'types'));
    }

    public function store(Request $request, Category $category)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'type' => ['required', 'string', 'max:255', Rule::in(array_keys(Attributes::typesList()))],
            'required' => 'nullable|string|max:255',
            'variants' => 'nullable|string',
            'sort' => 'required|integer',
        ]);

        $attribute = $category->attributes()->create([
            'name' => $request['name'],
            'type' => $request['type'],
            'required' => (bool)$request['required'],
            'variants' => array_map('trim', preg_split('#[\r\n]+#', $request['variants'])),
            'sort' => $request['sort'],
        ]);

        return redirect()->route('admin.adverts.categories.attributes.show', [$category, $attribute]);
    }

    public function show(Category $category, Attributes $attribute)
    {
        return view('admin.adverts.categories.attributes.show', compact('category', 'attribute'));
    }

    public function edit(Category $category, Attributes $attribute)
    {
        $types = Attributes::typesList();

        return view('admin.adverts.categories.attributes.edit', compact('category', 'attribute', 'types'));
    }

    public function update(Request $request, Category $category, Attributes $attribute)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'type' => ['required', 'string', 'max:255', Rule::in(array_keys(Attributes::typesList()))],
            'required' => 'nullable|string|max:255',
            'variants' => 'nullable|string',
            'sort' => 'required|integer',
        ]);

        $category->attributes()->findOrFail($attribute->id)->update([
            'name' => $request['name'],
            'type' => $request['type'],
            'required' => (bool)$request['required'],
            'variants' => array_map('trim', preg_split('#[\r\n]+#', $request['variants'])),
            'sort' => $request['sort'],
        ]);

        return redirect()->route('admin.adverts.categories.show', $category);
    }

    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('admin.adverts.categories.show', $category);
    }
}

app/Http/Controllers/Admin/Adverts/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Adverts;

use App\Entity\Adverts\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:admin-panel');
    }

    public function index()
    {
        $categories = Category::defaultOrder()->withDepth()->get();

        return view('admin.adverts.categories.index', compact('categories'));
    }

    public function create()
    {
        $parents = Category::defaultOrder()->withDepth()->get();

        return view('admin.adverts.categories.create', compact('parents'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'slug' => 'required|string|max:255',
            'parent' => 'nullable|integer|exists:advert_categories,id',
        ]);

        $category = Category::create([
            'name' => $request['name'],
            'slug' => $request['slug'],
            'parent_id' => $request['parent'],
        ]);

        return redirect()->route('admin.adverts.categories.show', $category);
    }

    public function show(Category $category)
    {
        $parentAttributes = $category->parentAttributes();
        $attributes = $category->attributes()->orderBy('sort')->get();

        return view('admin.adverts.categories.show', compact('category', 'attributes', 'parentAttributes'));
    }

    public function edit(Category $category)
    {
        $parents = Category::defaultOrder()->withDepth()->get();

        return view('admin.adverts.categories.edit', compact('category', 'parents'));
    }

    public function update(Request $request, Category $category)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'slug' => 'required|string|max:255',
            'parent' => 'nullable|integer|exists:advert_categories,id',
        ]);

        $category->update([
            'name' => $request['name'],
            'slug' => $request['slug'],
            'parent_id' => $request['parent'],
        ]);

        return redirect()->route('admin.adverts.categories.show', $category);
    }

    public function first(Category $category)
    {
        if ($first = $category->siblings()->defaultOrder()->first()) {
            $category->insertBeforeNode($first);
        }

        return redirect()->route('admin.adverts.categories.index');
    }

    public function up(Category $category)
    {
        $category->up();

        return redirect()->route('admin.adverts.categories.index');
    }

    public function down(Category $category)
    {
        $category->down();

        return redirect()->route('admin.adverts.categories.index');
    }

    public function last(Category $category)
    {
        if ($last = $category->siblings()->defaultOrder('desc')->first()) {
            $category->insertAfterNode($last);
        }

        return redirect()->route('admin.adverts.categories.index');
    }

    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('admin.adverts.categories.index');
    }
}

resources/views/admin/adverts/categories/_nav.blade.php
@include ('admin._nav', ['page' => 'adverts_categories'])

resources/views/admin/adverts/categories/create.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.adverts.categories._nav')

    <form method="POST" action="{{ route('admin.adverts.categories.store') }}">
        @csrf

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="slug" class="col-form-label">Slug</label>
            <input id="slug" type="text" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}" name="slug" value="{{ old('slug') }}" required>
            @if ($errors->has('slug'))
                <span class="invalid-feedback"><strong>{{ $errors->first('slug') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="parent" class="col-form-label">Parent</label>
            <select id="parent" class="form-control{{ $errors->has('parent') ? ' is-invalid' : '' }}" name="parent">
                <option value=""></option>
                @foreach ($parents as $parent)
                    <option value="{{ $parent->id }}"{{ $parent->id == old('parent') ? ' selected' : '' }}>
                        @for ($i = 0; $i < $parent->depth; $i++) &mdash; @endfor
                        {{ $parent->name }}
                    </option>
                @endforeach;
            </select>
            @if ($errors->has('parent'))
                <span class="invalid-feedback"><strong>{{ $errors->first('parent') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/adverts/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.adverts.categories._nav')

    <form method="POST" action="{{ route('admin.adverts.categories.update', $category) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $category->name) }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="slug" class="col-form-label">Slug</label>
            <input id="slug" type="text" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}" name="slug" value="{{ old('slug', $category->slug) }}" required>
            @if ($errors->has('slug'))
                <span class="invalid-feedback"><strong>{{ $errors->first('slug') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="parent" class="col-form-label">Parent</label>
            <select id="parent" class="form-control{{ $errors->has('parent') ? ' is-invalid' : '' }}" name="parent">
                <option value=""></option>
                @foreach ($parents as $parent)
                    <option value="{{ $parent->id }}"{{ $parent->id == old('parent', $category->parent_id) ? ' selected' : '' }}>
                        @for ($i = 0; $i < $parent->depth; $i++) &mdash; @endfor
                        {{ $parent->name }}
                    </option>
                @endforeach;
            </select>
            @if ($errors->has('parent'))
                <span class="invalid-feedback"><strong>{{ $errors->first('parent') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/adverts/categories/index.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.adverts.categories._nav')

    <p><a href="{{ route('admin.adverts.categories.create') }}" class="btn btn-success">Add Category</a></p>

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Name</th>
            <th>Slug</th>
            <th></th>
        </tr>
        </thead>
        <tbody>

        @foreach ($categories as $category)
            <tr>
                <td>
                    @for ($i = 0; $i < $category->depth; $i++) &mdash; @endfor
                    <a href="{{ route('admin.adverts.categories.show', $category) }}">{{ $category->name }}</a>
                </td>
                <td>{{ $category->slug }}</td>
                <td>
                    <div class="d-flex flex-row">
                        <form method="POST" action="{{ route('admin.adverts.categories.first', $category) }}" class="mr-1">
                            @csrf
                            <button class="btn btn-sm btn-outline-primary"><span class="fa fa-angle-double-up"> First</span></button>
                        </form>
                        <form method="POST" action="{{ route('admin.adverts.categories.up', $category) }}" class="mr-1">
                            @csrf
                            <button class="btn btn-sm btn-outline-primary"><span class="fa fa-angle-up"> Up</span></button>
                        </form>
                        <form method="POST" action="{{ route('admin.adverts.categories.down', $category) }}" class="mr-1">
                            @csrf
                            <button class="btn btn-sm btn-outline-primary"><span class="fa fa-angle-down"> Down</span></button>
                        </form>
                        <form method="POST" action="{{ route('admin.adverts.categories.last', $category) }}" class="mr-1">
                            @csrf
                            <button class="btn btn-sm btn-outline-primary"><span class="fa fa-angle-double-down"> Last</span></button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>
@endsection

resources/views/admin/adverts/categories/show.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.adverts.categories._nav')

    <div class="d-flex flex-row mb-3">
        <a href="{{ route('admin.adverts.categories.edit', $category) }}" class="btn btn-primary mr-1">Edit</a>
        <form method="POST" action="{{ route('admin.adverts.categories.destroy', $category) }}" class="mr-1">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger">Delete</button>
        </form>
    </div>

    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th>ID</th><td>{{ $category->id }}</td>
        </tr>
        <tr>
            <th>Name</th><td>{{ $category->name }}</td>
        </tr>
        <tr>
            <th>Slug</th><td>{{ $category->slug }}</td>
        </tr>
        <tbody>
        </tbody>
    </table>

    <p><a href="{{ route('admin.adverts.categories.attributes.create', $category) }}" class="btn btn-success">Add Attribute</a></p>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Sort</th>
            <th>Name</th>
            <th>Slug</th>
            <th>Required</th>
        </tr>
        </thead>
        <tbody>

        <tr><th colspan="4">Parent attributes</th></tr>

        @forelse ($parentAttributes as $attribute)
            <tr>
                <td>{{ $attribute->sort }}</td>
                <td>{{ $attribute->name }}</td>
                <td>{{ $attribute->type }}</td>
                <td>{{ $attribute->required ? 'Yes' : '' }}</td>
            </tr>
        @empty
            <tr><td colspan="4">None</td></tr>
        @endforelse

        <tr><th colspan="4">Own attributes</th></tr>

        @forelse ($attributes as $attribute)
            <tr>
                <td>{{ $attribute->sort }}</td>
                <td>
                    <a href="{{ route('admin.adverts.categories.attributes.show', [$category, $attribute]) }}">{{ $attribute->name }}</a>
                </td>
                <td>{{ $attribute->type }}</td>
                <td>{{ $attribute->required ? 'Yes' : '' }}</td>
            </tr>
        @empty
            <tr><td colspan="4">None</td></tr>
        @endforelse

        </tbody>
    </table>
@endsection