routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
//use App\Http\Middleware\FilledProfile;
use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('home');

//Route::get('/', function (){
//	return view('welcome');
//});

Auth::routes();

Route::get('/cabinet', 'Cabinet\HomeController@index')->name('cabinet');

//Route::get('/cabinet', 'Auth\LoginController@index')->name('login');

Route::get('/verify/{token})', 'Auth\RegisterController@verify')->name('register.verify');

//Route::get('/cabinet', 'Cabinet\HomeController@index')->name('cabinet.home');

Route::group(
	[
		'prefix' => 'cabinet',
		'as' => 'cabinet.',
		'namespace' => 'Cabinet',
		'middleware' => ['auth'],
	],
	function () {
		Route::get('/', 'HomeController@index')->name('home');

//		Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
//			Route::get('/', 'ProfileController@index')->name('home');
//			Route::get('/edit', 'ProfileController@edit')->name('edit');
//			Route::put('/update', 'ProfileController@update')->name('update');
//			Route::post('/phone', 'PhoneController@request');
//			Route::get('/phone', 'PhoneController@form')->name('phone');
//			Route::put('/phone', 'PhoneController@verify')->name('phone.verify');
//
//			Route::post('/phone/auth', 'PhoneController@auth')->name('phone.auth');
//		});
//
//		Route::get('favorites', 'FavoriteController@index')->name('favorites.index');
//		Route::delete('favorites/{advert}', 'FavoriteController@remove')->name('favorites.remove');
//
//		Route::resource('tickets', 'TicketController')->only(['index', 'show', 'create', 'store', 'destroy']);
//		Route::post('tickets/{ticket}/message', 'TicketController@message')->name('tickets.message');

//		Route::group([
//			'prefix' => 'adverts',
//			'as' => 'adverts.',
//			'namespace' => 'Adverts',
//			'middleware' => [App\Http\Middleware\FilledProfile::class],
//		], function () {
//			Route::get('/', 'AdvertController@index')->name('index');
//			Route::get('/create', 'CreateController@category')->name('create');
//			Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
//			Route::get('/create/advert/{category}/{region?}', 'CreateController@advert')->name('create.advert');
//			Route::post('/create/advert/{category}/{region?}', 'CreateController@store')->name('create.advert.store');
//
//			Route::get('/{advert}/edit', 'ManageController@editForm')->name('edit');
//			Route::put('/{advert}/edit', 'ManageController@edit');
//			Route::get('/{advert}/photos', 'ManageController@photosForm')->name('photos');
//			Route::post('/{advert}/photos', 'ManageController@photos');
//			Route::get('/{advert}/attributes', 'ManageController@attributesForm')->name('attributes');
//			Route::post('/{advert}/attributes', 'ManageController@attributes');
//			Route::post('/{advert}/send', 'ManageController@send')->name('send');
//			Route::post('/{advert}/close', 'ManageController@close')->name('close');
//			Route::delete('/{advert}/destroy', 'ManageController@destroy')->name('destroy');
		});

Route::group(
	[
		'prefix' => 'admin',
		'as' => 'admin.',
		'namespace' => 'Admin',
		'middleware' => ['auth', 'can:admin-panel'],
	],
	function () {
//		Route::post( '/ajax/upload/image', 'UploadController@image' )->name( 'ajax.upload.image' );

		Route::get( '/', 'HomeController@index' )->name( 'home' );
		Route::resource( 'users', 'UserController' );
		Route::get( '/users/{user}/roles', 'UserController@changeRoleView' )->name( 'user.roles' );
		Route::post( '/users/{user}/roles-edit', 'UserController@changeRoleEdit' )->name( 'user.roles-edit' );
//		Route::post( '/users/{user}/verify', 'UsersController@verify' )->name( 'users.verify' );

		Route::resource( 'regions', 'RegionController' );
		Route::group(['prefix' => 'adverts', 'as' => 'adverts.', 'namespace' => 'Adverts'], function () {

			Route::resource( 'categories', 'CategoryController' );

			Route::group(['prefix' => 'categories/{category}', 'as' => 'categories.'], function () {
				Route::post('/first', 'CategoryController@first')->name('first');
				Route::post('/up', 'CategoryController@up')->name('up');
				Route::post('/down', 'CategoryController@down')->name('down');
				Route::post('/last', 'CategoryController@last')->name('last');
				Route::resource('attributes', 'AttributeController')->except('index');
			});
		});
//
//		Route::resource( 'pages', 'PageController' );
//
//		Route::group( [ 'prefix' => 'pages/{page}', 'as' => 'pages.' ], function () {
//			Route::post( '/first', 'PageController@first' )->name( 'first' );
//			Route::post( '/up', 'PageController@up' )->name( 'up' );
//			Route::post( '/down', 'PageController@down' )->name( 'down' );
//			Route::post( '/last', 'PageController@last' )->name( 'last' );
//		} );
	});

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Users\CreateRequest;
use Exception;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;


class UserController extends Controller
{

	/**
	 * @var CheckUserRole
	 */
	private $checkUserRole;

	public function __construct()
	{
//		$this->middleware('can:admin-panel');
//		if ($this->checkUserRole->checkRole('ROLE_ADMIN') !== true){
//			abort(403);
//			die();
//		}
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @param Request $request
	 *
	 * @return Response
	 */
    public function index(Request $request)
    {
//    	if (Auth::user()->checkRole('ROLE_ADMIN') !== true){
//    		return abort(403);
//	    }
	    $query = User::orderByDesc('id');

	    if (!empty($value = $request->get('id'))) {
		    $query->where('id', $value);
	    }

	    if (!empty($value = $request->get('name'))) {
		    $query->where('name', 'like', '%' . $value . '%');
	    }

	    if (!empty($value = $request->get('email'))) {
		    $query->where('email', 'like', '%' . $value . '%');
	    }

	    if (!empty($value = $request->get('status'))) {
		    $query->where('status', $value);
	    }

	    if (!empty($value = $request->get('role'))) {
		    $query->where('role', 'like', '%' . $value . '%');
	    }

	    $users = $query->paginate(20);

	    $statuses = [
		    User::STATUS_WAIT => 'wait',
		    User::STATUS_ACTIVE => 'active',
	    ];

	    $roles = User::rolesList();

	    return view('admin.users.index', compact('users','statuses', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {

	    return view('admin.users.create');
    }

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param CreateRequest $request
	 *
	 * @return void
	 */
    public function store(CreateRequest $request)
    {

	    $user = User::new(
		    $request['name'],
		    $request['email'],
		    $request['status'],
		    $request['password']
	    );

	    return redirect()->route('admin.users.show', $user);
    }

	/**
	 * Display the specified resource.
	 *
	 * @param User $user
	 *
	 * @return Response
	 */
    public function show(User $user)
    {
	    return view('admin.users.show', compact('user'));
    }

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param User $user
	 *
	 * @return Response
	 */
    public function edit(User $user)
    {
	    return view('admin.users.edit', compact('user'));
    }

	/**
	 * Update the specified resource in storage.
	 *
	 * @param CreateRequest $request
	 * @param User $user
	 *
	 * @return Response
	 */
    public function update(CreateRequest $request, User $user)
    {
	    $user->update($request->only(['name', 'email']));

	    return redirect()->route('admin.users.show', $user);
    }

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param User $user
	 *
	 * @return Response
	 * @throws Exception
	 */
	public function destroy(User $user)
	{
		$user->delete();

		return redirect()->route('admin.users.index');
	}

	/**
	 * @param User $user
	 *
	 * @return RedirectResponse
	 */
	public function changeRoleView(User $user)
	{
		$roles = User::rolesList();
		return view('admin.users.roles', [
			'user' => $user,
			'roles' => $roles
		]);
	}

	/**
	 * @return RedirectResponse
	 */
	public function changeRoleEdit(User $user, Request $request)
	{
		$user->update([
			'role' => $request->role
		]);

		return redirect()->route('admin.users.index');
	}
}

resources/views/admin/users/_nav.blade.php
@include ('admin._nav', ['page' => 'users'])

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <form method="POST" action="{{ route('admin.users.store') }}">
        @csrf

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="email" class="col-form-label">E-Mail Address</label>
            <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>
            @if ($errors->has('email'))
                <span class="invalid-feedback"><strong>{{ $errors->first('email') }}</strong></span>
            @endif
        </div>
        <div class="form-group pt-2">
            <select class="custom-select{{ $errors->has('status') ? ' is-invalid' : '' }}" id="status" name="status" required>
                <option selected>Выберите статус</option>
                <option value="active">active</option>
                <option value="wait">wait</option>
            </select>
            @if ($errors->has('status'))
                <span class="invalid-feedback"><strong>{{ $errors->first('status') }}</strong></span>
            @endif
        </div>
{{--        <div class="form-group pt-2">--}}
{{--            <select class="custom-select {{ $errors->has('role') ? ' is-invalid' : '' }}" name="role" id="level" required>--}}
{{--                <option selected>Выберите доступ</option>--}}
{{--                <option value="ROLE_USER">User</option>--}}
{{--                <option value="ROLE_ADMIN">Admin</option>--}}
{{--                <option value="ROLE_MODERATOR">Moderator</option>--}}
{{--            </select>--}}
{{--            @if ($errors->has('role'))--}}
{{--                <span class="invalid-feedback"><strong>{{ $errors->first('role') }}</strong></span>--}}
{{--            @endif--}}
{{--        </div>--}}
        <div class="form-group">
            <label for="password" class="col-form-label">Password</label>
            <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password"  required>
            @if ($errors->has('password'))
                <span class="invalid-feedback"><strong>{{ $errors->first('password') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <form method="POST" action="{{ route('admin.users.update', $user) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $user->name) }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="email" class="col-form-label">E-Mail Address</label>
            <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email', $user->email) }}" required>
            @if ($errors->has('email'))
                <span class="invalid-feedback"><strong>{{ $errors->first('email') }}</strong></span>
            @endif
        </div>

{{--        <div class="form-group">--}}
{{--            <label for="role" class="col-form-label">Role</label>--}}
{{--            <select id="role" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="role">--}}
{{--                @foreach ($roles as $value => $label)--}}
{{--                    <option value="{{ $value }}"{{ $value === old('role', $user->role) ? ' selected' : '' }}>{{ $label }}</option>--}}
{{--                @endforeach;--}}
{{--            </select>--}}
{{--            @if ($errors->has('role'))--}}
{{--                <span class="invalid-feedback"><strong>{{ $errors->first('role') }}</strong></span>--}}
{{--            @endif--}}
{{--        </div>--}}

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')
    <div>
        <a href="{{ route('admin.users.create') }}" class="btn btn-success">
            Add User
        </a>
    </div>
    <div class="card mb-3">
        <div class="card-header">Filter</div>
        <div class="card-body">
            <form action="?" method="GET">
                <div class="row">
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label for="id" class="col-form-label">ID</label>
                            <input id="id" class="form-control" name="id" value="{{ request('id') }}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="name" class="col-form-label">Name</label>
                            <input id="name" class="form-control" name="name" value="{{ request('name') }}">
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label for="email" class="col-form-label">Email</label>
                            <input id="email" class="form-control" name="email" value="{{ request('email') }}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="status" class="col-form-label">Status</label>
                            <select id="status" class="form-control" name="status">
                                <option value=""></option>
                                @foreach ($statuses as $value => $label)
                                    <option value="{{ $value }}"{{ $value === request('status') ? ' selected' : '' }}>{{ $label }}</option>
                                @endforeach;
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="role" class="col-form-label">Role</label>
                            <select id="role" class="form-control" name="role">
                                <option value=""></option>
                                @foreach ($roles as $value => $label)
                                    <option value="{{ $value }}"{{ $value === request('role') ? ' selected' : '' }}>{{ $label }}</option>
                                @endforeach;
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label class="col-form-label">&nbsp;</label><br />
                            <button type="submit" class="btn btn-primary">Search</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Status</th>
            <th>Role</th>
        </tr>
        </thead>
        <tbody>

        @foreach ($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td><a href="{{ route('admin.users.show', $user) }}">{{ $user->name }}</a></td>
                <td>{{ $user->email }}</td>
                <td>
                    @if ($user->isWait())
                        <span class="badge badge-secondary">Waiting</span>
                    @endif
                    @if ($user->isActive())
                        <span class="badge badge-primary">Active</span>
                    @endif
                </td>
                <td>
                    @if ($user->isAdmin())
                        <span class="badge badge-danger">ROLE_ADMIN</span>
                    @endif
                    @if($user->isUser())
                        <span class="badge badge-secondary">ROLE_USER</span>
                    @endif
                    @if($user->isModerator())
                        <span class="badge badge-warning">ROLE_MODERATOR</span>
                    @endif
                </td>
                <td>
                    <a class="btn-primary" href="{{ route('admin.user.roles', $user) }}">
                        Add roles
                    </a>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>


    {{ $users->links() }}
@endsection

resources/views/admin/users/roles.blade.php
@extends('layouts.app')

@section('content')
    <form method="POST" action="{{ route('admin.user.roles-edit', $user) }}">
        @csrf
        @foreach($roles as $role)
            <div class="form-group d-flex justify-content-between">
                <label for="role" class="col-form-label">{{ $role }}</label>
                <input type="checkbox" id="role" class="form-control align-self-auto w-75" name="role[]" value="{{ $role }}"
                @if(in_array($role, $user->role))
                        checked="checked"
                @endif>
            </div>
        @endforeach

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <div class="d-flex flex-row mb-3">
        <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-primary mr-1">Edit</a>

{{--        @if ($user->isWait())--}}
{{--            <form method="POST" action="{{ route('admin.users.verify', $user) }}" class="mr-1">--}}
{{--                @csrf--}}
{{--                <button class="btn btn-success">Verify</button>--}}
{{--            </form>--}}
{{--        @endif--}}

        <form method="POST" action="{{ route('admin.users.destroy', $user) }}" class="mr-1">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger">Delete</button>
        </form>
    </div>

    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th>ID</th><td>{{ $user->id }}</td>
        </tr>
        <tr>
            <th>Name</th><td>{{ $user->name }}</td>
        </tr>
        <tr>
            <th>Email</th><td>{{ $user->email }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>
                @if ($user->status === null || $user->status === 'wait')
                    <span class="badge badge-secondary">Waiting</span>
                @endif
                @if ($user->status === 'active')
                    <span class="badge badge-primary">Active</span>
                @endif
            </td>
        </tr>
        <tr>
            <th>Role</th>
            <td>
                @foreach($user->role as $role)
                    [ {{ $role }} ]
                @endforeach
            </td>
        </tr>
        <tbody>
        </tbody>
    </table>

@endsection